### ISSUE TITLE
Finalize

### ISSUE THREAD

**Issue by willirath** [geomar-od/rasmus-cmems-downloads#16]
Let's list everything necessary for finalization of the download pipeline.

- [x] Restructure to put each step into a separated directory. (#13)
- [x] Rename "upload" to "download" (#14)
- [x] finalize Zarr containerisation (#9)
- [x] Document file and directory naming conventions (#6)
- [x] Generalize the download and conversion scripts (#15)

**Comment by eshchekinova** [comment]
Two issues are completed: rename "upload" to "download", generalize the download and conversion scripts.

**Comment by willirath** [comment]
Done.
